### ISSUE TITLE
coord.join(threads) problem

### ISSUE THREAD

**Issue by 527515025** [kevin28520/My-TensorFlow-tutorials#11]
Hello, when I run input_data.py with "01 cats vs dogs" code, I met the problem, please help fix it.

machine and could speed up CPU computations.
label: 0
label: 1
Traceback (most recent call last):
  File "/Users/yangyibo/GitWork/pythonLean/AI/猫狗识别/input_data.py", line 107, in <module>
    coord.join(threads)
  File "/Users/yangyibo/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/Users/yangyibo/anaconda3/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/Users/yangyibo/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/Users/yangyibo/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1063, in _single_operation_run
    target_list_as_strings, status, None)
  File "/Users/yangyibo/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/Users/yangyibo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got unknown format starting with '\000\000\000\001Bud1\000\000\020\000\000\000\010\000'
	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile)]]
[Finished in 6.5s with exit code 1]

**Comment by 527515025** [comment]
I've solved it. It's the sample I've prepared. There's a problem with the picture
