### ISSUE TITLE
cifar10 coord.join(threads)

### ISSUE THREAD

**Issue by jren2017** [kevin28520/My-TensorFlow-tutorials#6]
Hello, when I run cifar10.py code, I met the following problem, please help fix it.

Free memory: 10.31GiB
2017-10-08 00:37:31.452207: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-10-08 00:37:31.452210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-10-08 00:37:31.452215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0)
2017-10-08 00:37:31.865668: W tensorflow/core/framework/op_kernel.cc:1192] Not found: /home/kevin/tensorflow/CIFAR10/data/cifar-10-batches-bin/data_batch_1.bin
	 [[Node: input/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](input/FixedLengthRecordReaderV2, input/input_producer)]]
Traceback (most recent call last):
  File "/administrator/PycharmProjects/NN_Learning/Cifar/CIFAR10/cifar10.py", line 274, in <module>
    train()
  File "/administrator/PycharmProjects/NN_Learning/Cifar/CIFAR10/cifar10.py", line 218, in train
    coord.join(threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1235, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/kevin/tensorflow/CIFAR10/data/cifar-10-batches-bin/data_batch_2.bin
	 [[Node: input/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](input/FixedLengthRecordReaderV2, input/input_producer)]]
	 [[Node: input/Slice_1/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_13_input/Slice_1", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Process finished with exit code 1

**Comment by john911f** [comment]
You are using Kevin's data_dir path:

NotFoundError: /home/kevin/tensorflow/CIFAR10/data/cifar-10-batches-bin/data_batch_2.bin

Change it to your own dir path.
