### ISSUE TITLE
new version error

### ISSUE THREAD

**Issue by hahahaqinqin** [kevin28520/My-TensorFlow-tutorials#9]
runfile('C:/Users/yuyangliu/cat vs dog/new_version/train_and_val.py', wdir='C:/Users/yuyangliu/cat vs dog/new_version')

run_training()
There are 12500 cats
There are 12500 dogs
Traceback (most recent call last):

  File "<ipython-input-2-0683f80cdbe4>", line 1, in <module>
    run_training()

  File "C:/Users/yuyangliu/cat vs dog/new_version/train_and_val.py", line 54, in run_training
    loss = model.losses(logits, y_)

  File "C:\Users\yuyangliu\cat vs dog\new_version\model.py", line 116, in losses
    (logits=logits, labels=labels, name='xentropy_per_example')

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1690, in sparse_softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 2486, in _sparse_softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 589, in apply_op
    param_name=input_name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))

TypeError: Value passed to parameter 'labels' has DataType int16 not in list of allowed values: int32, int64

When I training the data. it was wrong.

**Comment by kevin28520** [comment]
就用中文说了：看错误提示，写的很清楚，labels 变量的数据类型不符合要求，需要Int32 或者 Int64， 给的是int16,
你需要多动手解决Bug

**Comment by tomoya92** [comment]
改成int32后会报一个新的错误

还需要把下面代码改一下, train_and_val.py

第101行改成 `summary_str = sess.run(summary_op, feed_dict={x: tra_images, y_: tra_labels})`

第109行改成 `summary_str = sess.run(summary_op, feed_dict={x: val_images, y_: val_labels})`

**Comment by bupt-steven** [comment]
@tomoya92 这个你的泛化能力怎么样？我这在测试集上成功率只有70%啊

**Comment by tomoya92** [comment]
我跑完也差不多70%左右

**Comment by bupt-steven** [comment]
@tomoya92 这个随机的期望应该50%，70%的话，还是有点低吧

**Comment by liyanfei18** [comment]
改了101和109也不行啊，还是说没有喂进去数据

**Comment by bupt-steven** [comment]
这个程序，我发一个打假申明：
大家认真看他的model softmax函数 101行：

        softmax_linear = tf.add(tf.matmul(local4, weights), biases, name='softmax_linear')

并没有用tf.nn.softmax 的任何函数，就只是做了加法。这个根本没有softmax。所以其实等于是做了线性拟合。肯定迅速就loss很小了，训练集上就100%了

**Comment by kevin28520** [comment]
@bupt-steven 这个repo不打算更新了，可能有些代码与现在的tensorflow版本不一致，抱歉。
关于你说的“这个根本没有softmax”问题，**实际情况是：确实使用了softmax()**，因为根据tensorflow官网api说明可以知道，softmax函数已经包含在loss function里面了，所以这里没有必要再使用一次，请参考这个函数：
[https://www.tensorflow.org/api_docs/python/tf/nn/softmax_cross_entropy_with_logits](url)
，里面有这么一个说明:

> WARNING: This op expects unscaled logits, since it performs a softmax on logits internally for efficiency. Do not call this op with the output of softmax, as it will produce incorrect results.

主要意思是：这个loss function会在**内部使用softmax**

**Comment by bupt-steven** [comment]
@kevin28520 学到了，可以可以
